from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.colors import HexColor, white
from reportlab.platypus import Paragraph
from reportlab.lib.styles import getSampleStyleSheet


# --------------------------------------------------
# TEXT WRAPPING (used for violation descriptions)
# --------------------------------------------------

def wrap_text(text, max_len=65):
    words = text.split()
    lines = []
    current = ""

    for word in words:
        if len(current + word) < max_len:
            current += word + " "
        else:
            lines.append(current.strip())
            current = word + " "

    lines.append(current.strip())
    return lines


# --------------------------------------------------
# FOOTER
# --------------------------------------------------

def draw_footer(c, width, page_number):

    c.setStrokeColor(HexColor("#CBD5F5"))
    c.line(50, 60, width - 50, 60)

    c.setFont("Helvetica-Oblique", 9)

    c.drawString(
        50,
        40,
        "Generated by Policy Compliance Intelligence AI System"
    )

    c.drawRightString(
        width - 50,
        40,
        f"Page {page_number}"
    )


# --------------------------------------------------
# PAGE BREAK HANDLER
# --------------------------------------------------

def new_page(c, width, height, page_number):

    draw_footer(c, width, page_number)

    c.showPage()

    page_number += 1

    y = height - 50

    return y, page_number


# --------------------------------------------------
# PDF REPORT
# --------------------------------------------------

def generate_pdf_report(data, path):

    c = canvas.Canvas(path, pagesize=letter)

    width, height = letter
    y = height - 50
    page_number = 1

    score = data["compliance_score"]

    styles = getSampleStyleSheet()
    paragraph_style = styles["Normal"]
    paragraph_style.fontName = "Helvetica"
    paragraph_style.fontSize = 11
    paragraph_style.leading = 15

    # --------------------------------------------------
    # HEADER
    # --------------------------------------------------

    c.setFont("Helvetica-Bold", 22)
    c.drawString(50, y, "Policy Compliance Report")

    y -= 35

    c.setStrokeColor(HexColor("#CBD5F5"))
    c.line(50, y, width - 50, y)

    y -= 30

    # --------------------------------------------------
    # STATUS BANNER
    # --------------------------------------------------

    if score >= 80:
        banner_color = HexColor("#16A34A")
        status = "COMPLIANT"
    elif score >= 50:
        banner_color = HexColor("#F59E0B")
        status = "PARTIALLY COMPLIANT"
    else:
        banner_color = HexColor("#DC2626")
        status = "NON-COMPLIANT"

    c.setFillColor(banner_color)
    c.rect(50, y, 500, 25, fill=1)

    c.setFillColor(white)
    c.setFont("Helvetica-Bold", 12)
    c.drawString(60, y + 7, f"COMPLIANCE STATUS: {status}")

    c.setFillColor(HexColor("#000000"))

    y -= 40

    # --------------------------------------------------
    # META INFORMATION
    # --------------------------------------------------

    c.setFont("Helvetica", 11)

    c.drawString(50, y, f"Run ID: {data['run_id']}")
    y -= 18

    c.drawString(50, y, f"Timestamp: {data['timestamp']}")
    y -= 18

    c.drawString(50, y, f"Rule Version: {data['rule_version']}")

    y -= 30

    c.setStrokeColor(HexColor("#CBD5F5"))
    c.line(50, y, width - 50, y)

    y -= 25

    # --------------------------------------------------
    # COMPLIANCE SUMMARY
    # --------------------------------------------------

    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Compliance Summary")

    y -= 25

    if score >= 80:
        score_color = HexColor("#16A34A")
    elif score >= 50:
        score_color = HexColor("#F59E0B")
    else:
        score_color = HexColor("#DC2626")

    c.setFillColor(score_color)
    c.rect(60, y - 5, 90, 24, fill=1)

    c.setFillColor(white)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(70, y + 2, f"{score}%")

    c.setFillColor(HexColor("#000000"))
    c.setFont("Helvetica", 12)
    c.drawString(160, y + 2, "Compliance Score")

    y -= 25

    c.setFont("Helvetica", 11)
    c.drawString(60, y, f"Risk Level: {data['risk_level']}")

    y -= 30

    c.setStrokeColor(HexColor("#CBD5F5"))
    c.line(50, y, width - 50, y)

    y -= 25

    # --------------------------------------------------
    # VIOLATIONS
    # --------------------------------------------------

    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Detected Violations")

    y -= 20

    c.setFont("Helvetica-Bold", 11)
    c.drawString(60, y, "Rule Description")
    c.drawString(420, y, "Severity")

    y -= 10
    c.line(50, y, 550, y)

    y -= 15

    c.setFont("Helvetica", 11)

    if data["violations"]:

        for v in data["violations"]:

            if y < 100:
                y, page_number = new_page(c, width, height, page_number)

            rule_text = v["description"]
            severity = v["severity"]

            lines = wrap_text(rule_text)

            c.drawString(60, y, lines[0])

            if severity == "critical":
                c.setFillColor(HexColor("#DC2626"))
            elif severity == "minor":
                c.setFillColor(HexColor("#F59E0B"))
            else:
                c.setFillColor(HexColor("#000000"))

            c.drawString(420, y, severity)

            c.setFillColor(HexColor("#000000"))

            y -= 16

            for line in lines[1:]:

                if y < 100:
                    y, page_number = new_page(c, width, height, page_number)

                c.drawString(60, y, line)
                y -= 14

            y -= 6

    else:

        c.drawString(60, y, "No violations detected.")
        y -= 20

    y -= 10

    c.setStrokeColor(HexColor("#CBD5F5"))
    c.line(50, y, width - 50, y)

    y -= 25

    # --------------------------------------------------
    # RECOMMENDATIONS
    # --------------------------------------------------

    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Policy Improvement Recommendations")

    y -= 20

    suggestions = data.get("suggestions", [])

    if suggestions:

        for suggestion in suggestions:

            clean = suggestion.replace("```json", "").replace("```", "").strip()

            paragraph = Paragraph(f"• {clean}", paragraph_style)

            w, h = paragraph.wrap(480, height)

            if y - h < 80:
                y, page_number = new_page(c, width, height, page_number)

            paragraph.drawOn(c, 60, y - h)

            y -= h + 10

    else:

        paragraph = Paragraph("No improvement recommendations required.", paragraph_style)

        w, h = paragraph.wrap(480, height)

        if y - h < 80:
            y, page_number = new_page(c, width, height, page_number)

        paragraph.drawOn(c, 60, y - h)

        y -= h + 10

    # --------------------------------------------------
    # FINAL FOOTER
    # --------------------------------------------------

    draw_footer(c, width, page_number)

    c.save()